name: example_contacts
description: Пример архитектуры отображения контактов (абоненты и группы)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fpdart: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
